# Pandas

https://pandas.pydata.org/docs/user_guide/index.html

# Agenda

- Introduction to Pandas

- Understading series and DataFrames
- Loading different data types format files
- connecting to database
- attributes and underlying dataframes
- Descriptive statistics
- Accessing subset of data 
- Handling missing data
- Dropping row and cols
- Handle Duplicates
- Function Application: map, applymap, groupby, rolling, str
- Merge, join and concat
- pivoting the table
- Noramlizing json
- Tidying Data  melt , pivoting

# Introduction to Data Wrangling and Pandas

- getting the data , reading the data from different source
- cleaning the data
- Structure the data
- store the data

- https://www.datarevenue.com/en-blog/pandas-vs-dask-vs-vaex-vs-modin-vs-rapids-vs-ray

## Pandas
-  libarary , package in python used for analysis
- can handle different datatypes
- pandas take a data in a tabular format
- fast , programmable and easy to use than spreadsheet
- has many functionality for data analysis
- support databases

# Tidying of data

- http://vita.had.co.nz/papers/tidy-data.pdf

## import pandas

In [6]:
import pandas as pd
import numpy as np

In [2]:
pd.__version__

'1.1.3'

## Understanding series and Dataframe

- Series is a one dimensional array
- Series can have any data type( int,str,float,python obj)
- comibination of multiple series create a DataFrame

In [3]:
ser1=pd.Series(data=[1,2,3,4,123,12])

In [4]:
ser1

0      1
1      2
2      3
3      4
4    123
5     12
dtype: int64

In [5]:
type(ser1)

pandas.core.series.Series

In [9]:
pd.Series(data=np.random.rand(5),index=["A","B","C","D","E"])

A    0.455994
B    0.559643
C    0.954559
D    0.468623
E    0.471086
dtype: float64

In [10]:
pd.Series(data=np.random.rand(5),index=list("ABCDE"))

A    0.985814
B    0.888354
C    0.196050
D    0.443697
E    0.220668
dtype: float64

In [11]:
# pass as a dict 
# no need to pass the index it take from the dict key

pd.Series(data={"A":1,"B":2,"C":3,"D":4})

A    1
B    2
C    3
D    4
dtype: int64

In [14]:
pd.Series(data={"A":1,"B":2,"C":3,"D":4}, index=["C","D","V","P","Z"])
# return the value witht he key that is present in the index arg

C    3.0
D    4.0
V    NaN
P    NaN
Z    NaN
dtype: float64

In [17]:
ser1=pd.Series(data=np.random.rand(5),index=["A","B","C","D","E"],dtype="object",name="column_1")

In [20]:
ser1.name

'column_1'

In [21]:
ser1

A    0.618965
B     0.70742
C    0.382996
D    0.907143
E    0.452841
Name: column_1, dtype: object

In [22]:
pd.Series(12)

0    12
dtype: int64

In [23]:
pd.Series(12,index=list("abcde"))

a    12
b    12
c    12
d    12
e    12
dtype: int64

In [30]:
ser2=pd.Series(np.random.randn(100),index=list(range(100)),name="col_1")

In [31]:
ser2

0     0.706404
1     0.478872
2     1.433578
3     0.935689
4     0.892338
        ...
95   -0.400143
96    1.482444
97    1.557180
98    0.522748
99    0.444828
Name: col_1, Length: 100, dtype: float64

In [34]:
print(f"mean--->{ser2.mean()}")
print(f"std---->{ser2.std()}")
print(f"var---->{ser2.var()}")

mean--->0.17629564180446824
std---->1.1423367881622104
var---->1.3049333375887546

In [36]:
ser2[:4]

0    0.706404
1    0.478872
2    1.433578
3    0.935689
Name: col_1, dtype: float64

In [37]:
ser2[10:20:2]

10    0.752812
12   -0.167107
14   -0.201626
16    0.022253
18    1.413070
Name: col_1, dtype: float64

In [39]:
ser2>0.5

0      True
1     False
2      True
3      True
4      True
      ...
95    False
96     True
97     True
98     True
99    False
Name: col_1, Length: 100, dtype: bool

In [40]:
ser2[ser2>0.5]

0     0.706404
2     1.433578
3     0.935689
4     0.892338
6     1.936204
7     1.070782
10    0.752812
18    1.413070
21    0.756641
23    3.136685
25    0.886078
31    0.775247
33    0.659694
39    0.557250
41    2.459123
42    2.863275
45    1.396853
48    3.177618
53    0.739545
56    0.541241
64    0.804588
70    1.328408
71    1.784507
72    1.774160
74    1.240486
75    0.834945
76    0.719496
77    1.923144
84    0.977068
85    3.185122
89    0.888037
90    2.199719
91    1.057345
94    0.995143
96    1.482444
97    1.557180
98    0.522748
Name: col_1, dtype: float64

In [45]:
ser2.where(ser2>0.5,other=0)

0     0.706404
1     0.000000
2     1.433578
3     0.935689
4     0.892338
        ...
95    0.000000
96    1.482444
97    1.557180
98    0.522748
99    0.000000
Name: col_1, Length: 100, dtype: float64

In [48]:
type(ser2.to_numpy())

numpy.ndarray

In [49]:
ser1=pd.Series(data=np.random.rand(5),index=["A","B","C","D","E"],dtype="object",name="column_1")

In [52]:
ser1[0:4]

A    0.845693
B      0.5493
C    0.557956
D    0.982379
Name: column_1, dtype: object

In [54]:
ser1["A":"C"]

A    0.845693
B      0.5493
C    0.557956
Name: column_1, dtype: object

In [56]:
ser1["C"]=1
ser1

A    0.845693
B      0.5493
C           1
D    0.982379
E    0.855611
Name: column_1, dtype: object

In [57]:
ser1[[0,2,1]]

A    0.845693
C           1
B      0.5493
Name: column_1, dtype: object

In [62]:
ser1.append(pd.Series([1,2,3]),ignore_index=True,)

0    0.845693
1      0.5493
2           1
3    0.982379
4    0.855611
5           1
6           2
7           3
dtype: object

In [63]:
ser_nan=pd.Series(data={"A":1,"B":2,"C":3,"D":4}, index=["C","D","V","P","Z"])
# return the value witht he key that is present in the index arg

In [68]:
ser_nan.fillna(3.4)

C    3.0
D    4.0
V    3.4
P    3.4
Z    3.4
dtype: float64

### vectorization

In [72]:
ser1+10

A    10.8457
B    10.5493
C         11
D    10.9824
E    10.8556
Name: column_1, dtype: object

In [73]:
ser1*10

A    8.45693
B      5.493
C         10
D    9.82379
E    8.55611
Name: column_1, dtype: object

In [75]:
ser1[1:]+ser1[:-1]

A        NaN
B     1.0986
C          2
D    1.96476
E        NaN
Name: column_1, dtype: object

In [76]:
ser1[2:]+ser1[:-1]

A        NaN
B        NaN
C          2
D    1.96476
E        NaN
Name: column_1, dtype: object

In [87]:
ser3=pd.Series(data=[1,2,3,"c"],index=[1,1,2,3])
ser4=pd.Series(data=[1,2,3,"c"],index=[0,1,1,3])

In [93]:
ser3

1    1
1    2
2    3
3    c
dtype: object

In [89]:
ser4

0    1
1    2
1    3
3    c
dtype: object

In [90]:
ser3[1]

1    1
1    2
dtype: object

In [91]:
ser3+ser4

0    NaN
1      3
1      4
1      4
1      5
2    NaN
3     cc
dtype: object

In [96]:
ser3.name="test"

In [99]:
ser3.rename("testwetset")

1    1
1    2
2    3
3    c
Name: testwetset, dtype: object

In [104]:
ser1.min()

0.5493004997270213

In [109]:
ser1.apply(np.abs)

A    0.845693
B      0.5493
C           1
D    0.982379
E    0.855611
Name: column_1, dtype: object

In [110]:
ser1.apply(lambda x: x+10)

A    10.845693
B    10.549300
C    11.000000
D    10.982379
E    10.855611
Name: column_1, dtype: float64

In [111]:
ser1+10

A    10.8457
B    10.5493
C         11
D    10.9824
E    10.8556
Name: column_1, dtype: object

# Dataframe

- 2-Dimesional collection. of series
- tablular form ( structured record or data
- act like a 2D- numpy

In [117]:
ser3=pd.Series(data=[1,2,3,4])
ser4=pd.Series(data=[5,6,7,8])
df=pd.DataFrame({"A":ser3,"B":ser4})

In [118]:
df

   A  B
0  1  5
1  2  6
2  3  7
3  4  8

In [120]:
type(pd.DataFrame(ser3))

pandas.core.frame.DataFrame

In [122]:
pd.DataFrame(ser3,columns=["A"])

   A
0  1
1  2
2  3
3  4

In [123]:
d={"Age":[11,12,14,16,18],
    "height":[130,135,140,150,160],
    "weight":[30,35,40,55,60]}

In [127]:
df=pd.DataFrame(d)

In [129]:
df["occ"]=["a","b","c","d","e"]

In [130]:
df

   Age  height  weight occ
0   11     130      30   a
1   12     135      35   b
2   14     140      40   c
3   16     150      55   d
4   18     160      60   e

In [133]:
user=[123,124,156,145]
platform=["facebook","twitter","insta","snapchat"]

In [135]:
pd.DataFrame(list(zip(user,platform)),columns=["user_id","platform"])

   user_id  platform
0      123  facebook
1      124   twitter
2      156     insta
3      145  snapchat

In [139]:
data=np.ones((2,),dtype=[
    ("A","f4"),
    ("B","i4"),
    ("C","f8")
])
data

array([(1., 1, 1.), (1., 1, 1.)],
      dtype=[('A', '<f4'), ('B', '<i4'), ('C', '<f8')])

In [142]:
data["C"]

array([1., 1.])

In [143]:
pd.DataFrame(data)

     A  B    C
0  1.0  1  1.0
1  1.0  1  1.0

In [146]:
pd.DataFrame(data=d,index=list("abcde"),columns=["Age","height"])

   Age  height
a   11     130
b   12     135
c   14     140
d   16     150
e   18     160

In [171]:
a=pd.DataFrame(np.random.randint(1,10,size=(10,10)),
             index=list("ABCDEFGHIJ"),
             columns=list("abcdefghij")
            )

In [180]:
data=((1,2,3,4,5),(6,7,8,9,10)) # iterable (()),[[]]
pd.DataFrame(data)

   0  1  2  3   4
0  1  2  3  4   5
1  6  7  8  9  10

In [181]:
dict_tup={
    ("a","a"):{"A":10,"B":11},
     ("a","b"):{"A":10,"B":11},
     ("b","a"):{"A":10,"B":11},
     ("b","b"):{"A":10,"B":11},
    
}

In [186]:
dict_tup[("a","b")]

{'A': 10, 'B': 11}

In [188]:
df=pd.DataFrame(dict_tup)

In [189]:
df

    a       b
    a   b   a   b
A  10  10  10  10
B  11  11  11  11

In [190]:
df.columns

MultiIndex([('a', 'a'),
            ('a', 'b'),
            ('b', 'a'),
            ('b', 'b')],
           )

In [192]:
df[("a","a")]

A    10
B    11
Name: (a, a), dtype: int64

In [193]:
df[("a","b")]

A    10
B    11
Name: (a, b), dtype: int64

In [196]:
df[("a","b")].name

('a', 'b')

In [206]:
dict_tup={
    "a":{"A":[10,11,12],"B":[11,12,13]},
     "b":{"A":{10,11,12},"B":11},
     "aa":{"A":10,"B":11},
     "bb":{"A":10,"B":11},
    "dd":{"A":{"B":12}}
    
}

In [207]:
new_df=pd.DataFrame(dict_tup)

In [208]:
new_df

              a             b  aa  bb         dd
A  [10, 11, 12]  {10, 11, 12}  10  10  {'B': 12}
B  [11, 12, 13]            11  11  11        NaN

In [216]:
new_df.dd["A"]["B"]

12

In [212]:
new_df.a["A"][2]

12

In [237]:
dict_tuple={
    ("Month","DAY1"):{("SUN","MAX"):20,("SUN","MIN"):10},
    ("Month","DAY2"):{("SUN","MAX"):25,("SUN","MIN"):20},
    
}

In [238]:
dict_tuple

{('Month', 'DAY1'): {('SUN', 'MAX'): 20, ('SUN', 'MIN'): 10},
 ('Month', 'DAY2'): {('SUN', 'MAX'): 25, ('SUN', 'MIN'): 20}}

In [240]:
df=pd.DataFrame(dict_tuple)

In [243]:
df

        Month
         DAY1 DAY2
SUN MAX    20   25
    MIN    10   20

In [242]:
df.columns

MultiIndex([('Month', 'DAY1'),
            ('Month', 'DAY2')],
           )

In [244]:
df.index

MultiIndex([('SUN', 'MAX'),
            ('SUN', 'MIN')],
           )

In [248]:
df.Month.DAY2.SUN.MAX

25

In [250]:
df[("Month","DAY2")][("SUN","MAX")]

25

In [251]:
df[("Month","DAY2")]["SUN"]["MAX"]

25

In [253]:
df[("Month","DAY2")][0]

25

In [255]:
df.T

           SUN
           MAX MIN
Month DAY1  20  10
      DAY2  25  20

In [258]:
from dataclasses import make_dataclass
from collections import namedtuple

In [269]:
name=namedtuple("name",(("age","height")))
name(12,140)

name(age=12, height=140)

In [270]:
pd.DataFrame([name(10,140.0),name(12,145),name(18,160)])

   age  height
0   10   140.0
1   12   145.0
2   18   160.0

In [263]:
name=make_dataclass("name",[("age",int),("height",float)])

In [267]:
df=pd.DataFrame([name(10,140.0),name(12,145),name(18,160)])

In [268]:
df.dtypes

age         int64
height    float64
dtype: object

In [271]:
df["age_height"]=df["age"]*df["height"]

In [272]:
df

   age  height  age_height
0   10   140.0      1400.0
1   12   145.0      1740.0
2   18   160.0      2880.0

In [273]:
del df["age_height"]

In [274]:
df

   age  height
0   10   140.0
1   12   145.0
2   18   160.0

In [279]:
df[(df["height"]>140) & (df["height"]>145)]

   age  height
2   18   160.0

In [288]:
(df["height"]>140) and (df["height"]>145)

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [293]:
a=df.where(df["age"]>12)
a.dropna()

    age  height
2  18.0   160.0

In [292]:
df[df["age"]>12]

   age  height
2   18   160.0

#### assign method

In [295]:
df.assign(height_age=df["age"]*df["height"])

   age  height  height_age
0   10   140.0      1400.0
1   12   145.0      1740.0
2   18   160.0      2880.0

In [297]:
df.assign(**{"height_age":df["age"]*df["height"]})

   age  height  height_age
0   10   140.0      1400.0
1   12   145.0      1740.0
2   18   160.0      2880.0

## Loading different files
- text
    - csv
    - json
    - HTML
    - fixed text file
- binary_file
    - HDF5
    - parquet
    - SAS
    - SPSS
    - feather
    - pickle
  
- sql
    - SQL
    - BigQuery

In [298]:
pd.read_csv("https://gist.githubusercontent.com/curran/a08a1080b88344b0c8a7/raw/0e7a9b0a5d22642a06d3d5b9bcbad9890c8ee534/iris.csv")

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [299]:
d=("A,B,C\n"
  "D,E,F\n"
  "H,I,j\n")

In [301]:
print(d)

A,B,C
D,E,F
H,I,j

In [303]:
import io

In [304]:
pd.read_csv(io.StringIO(d))

   A  B  C
0  D  E  F
1  H  I  j

In [306]:
pd.read_csv("/Users/bhuwankarki/Desktop/DS-ML-2021-04/Data/house_rental_data.csv.txt").head()

,Unnamed: 0,Sqft,Floor,TotalFloor,Bedroom,Living.Room,Bathroom,Price
0,1,1177.698,2,7,2,2,2,62000
1,2,2134.800,5,7,4,2,2,78000
2,3,1138.560,5,7,2,2,1,58000
3,4,1458.780,2,7,3,2,2,45000
4,5,967.776,11,14,3,2,2,45000

In [311]:
pd.read_csv("/Users/bhuwankarki/Desktop/DS-ML-2021-04/Data/house_rental_data.csv.txt",
           usecols=[1,2],skiprows=1).head()

   1177.698   2
0  2134.800   5
1  1138.560   5
2  1458.780   2
3   967.776  11
4  1127.886  11

In [312]:
url="https://gist.githubusercontent.com/curran/a08a1080b88344b0c8a7/raw/0e7a9b0a5d22642a06d3d5b9bcbad9890c8ee534/index.html"

In [315]:
pd.read_csv(url,engine="python",error_bad_lines=False)

Skipping line 16: Expected 1 fields in line 16, saw 3
Skipping line 25: Expected 1 fields in line 25, saw 3

                                      <!DOCTYPE html>
0                                              <head>
1                              <meta charset="utf-8">
2     <script src="https://cdnjs.cloudflare.com/aj...
3                                             </head>
4                                              <body>
5                                            <script>
6                              function render(data){
7                                   d3.select("body")
8                                      .append("pre")
9                                                   }
10                                  function type(d){
11                  d.sepal_length = +d.sepal_length;
12                   d.sepal_width  = +d.sepal_width;
13                  d.petal_length = +d.petal_length;
14                   d.petal_width  = +d.petal_width;
15                                          return d;
16                                                  }
17                                          </script>
18                                            </body>

In [317]:
data='''
<!DOCTYPE html>
<html>
<head>
<style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}
</style>
</head>
<body>

<h2>HTML Table</h2>

<table>
  <tr>
    <th>Company</th>
    <th>Contact</th>
    <th>Country</th>
  </tr>
  <tr>
    <td>Alfreds Futterkiste</td>
    <td>Maria Anders</td>
    <td>Germany</td>
  </tr>
  <tr>
    <td>Centro comercial Moctezuma</td>
    <td>Francisco Chang</td>
    <td>Mexico</td>
  </tr>
  <tr>
    <td>Ernst Handel</td>
    <td>Roland Mendel</td>
    <td>Austria</td>
  </tr>
  <tr>
    <td>Island Trading</td>
    <td>Helen Bennett</td>
    <td>UK</td>
  </tr>
  <tr>
    <td>Laughing Bacchus Winecellars</td>
    <td>Yoshi Tannamuri</td>
    <td>Canada</td>
  </tr>
  <tr>
    <td>Magazzini Alimentari Riuniti</td>
    <td>Giovanni Rovelli</td>
    <td>Italy</td>
  </tr>
</table>

</body>
</html>

'''

In [318]:
pd.read_html(data)

[                        Company           Contact  Country
 0           Alfreds Futterkiste      Maria Anders  Germany
 1    Centro comercial Moctezuma   Francisco Chang   Mexico
 2                  Ernst Handel     Roland Mendel  Austria
 3                Island Trading     Helen Bennett       UK
 4  Laughing Bacchus Winecellars   Yoshi Tannamuri   Canada
 5  Magazzini Alimentari Riuniti  Giovanni Rovelli    Italy]

In [324]:
pd.read_csv("https://gist.githubusercontent.com/curran/a08a1080b88344b0c8a7/raw/0e7a9b0a5d22642a06d3d5b9bcbad9890c8ee534/iris.csv",
            skiprows=1,engine="c",
               verbose=True)

Tokenization took: 0.02 ms
Type conversion took: 0.36 ms
Parser memory cleanup took: 0.00 ms

     5.1  3.5  1.4  0.2     setosa
0    4.9  3.0  1.4  0.2     setosa
1    4.7  3.2  1.3  0.2     setosa
2    4.6  3.1  1.5  0.2     setosa
3    5.0  3.6  1.4  0.2     setosa
4    5.4  3.9  1.7  0.4     setosa
..   ...  ...  ...  ...        ...
144  6.7  3.0  5.2  2.3  virginica
145  6.3  2.5  5.0  1.9  virginica
146  6.5  3.0  5.2  2.0  virginica
147  6.2  3.4  5.4  2.3  virginica
148  5.9  3.0  5.1  1.8  virginica

[149 rows x 5 columns]

In [334]:
pd.read_csv("https://gist.githubusercontent.com/curran/a08a1080b88344b0c8a7/raw/0e7a9b0a5d22642a06d3d5b9bcbad9890c8ee534/iris.csv",
            index_col="species",
            converters={"petal_length": lambda x:str(x)},
               verbose=True).head()

Tokenization took: 0.02 ms
Type conversion took: 0.56 ms
Parser memory cleanup took: 0.00 ms

         sepal_length  sepal_width petal_length  petal_width
species
setosa            5.1          3.5          1.4          0.2
setosa            4.9          3.0          1.4          0.2
setosa            4.7          3.2          1.3          0.2
setosa            4.6          3.1          1.5          0.2
setosa            5.0          3.6          1.4          0.2

In [341]:
data=pd.read_csv("https://gist.githubusercontent.com/curran/a08a1080b88344b0c8a7/raw/0e7a9b0a5d22642a06d3d5b9bcbad9890c8ee534/iris.csv",
            index_col="species",
            converters={"petal_length": lambda x:str(x)},
            chunksize=50,
               verbose=True)

In [338]:
for i in data:
    print(i)

Tokenization took: 0.01 ms
Type conversion took: 0.26 ms
Parser memory cleanup took: 0.01 ms
         sepal_length  sepal_width petal_length  petal_width
species
setosa            5.1          3.5          1.4          0.2
setosa            4.9          3.0          1.4          0.2
setosa            4.7          3.2          1.3          0.2
setosa            4.6          3.1          1.5          0.2
setosa            5.0          3.6          1.4          0.2
setosa            5.4          3.9          1.7          0.4
setosa            4.6          3.4          1.4          0.3
setosa            5.0          3.4          1.5          0.2
setosa            4.4          2.9          1.4          0.2
setosa            4.9          3.1          1.5          0.1
setosa            5.4          3.7          1.5          0.2
setosa            4.8          3.4          1.6          0.2
setosa            4.8          3.0          1.4          0.1
setosa            4.3          3.0          1.1          0.1
setosa            5.8          4.0          1.2          0.2
setosa            5.7          4.4          1.5          0.4
setosa            5.4          3.9          1.3          0.4
setosa            5.1          3.5          1.4          0.3
setosa            5.7          3.8          1.7          0.3
setosa            5.1          3.8          1.5          0.3
setosa            5.4          3.4          1.7          0.2
setosa            5.1          3.7          1.5          0.4
setosa            4.6          3.6          1.0          0.2
setosa            5.1          3.3          1.7          0.5
setosa            4.8          3.4          1.9          0.2
setosa            5.0          3.0          1.6          0.2
setosa            5.0          3.4          1.6          0.4
setosa            5.2          3.5          1.5          0.2
setosa            5.2          3.4          1.4          0.2
setosa            4.7          3.2          1.6          0.2
setosa            4.8          3.1          1.6          0.2
setosa            5.4          3.4          1.5          0.4
setosa            5.2          4.1          1.5          0.1
setosa            5.5          4.2          1.4          0.2
setosa            4.9          3.1          1.5          0.1
setosa            5.0          3.2          1.2          0.2
setosa            5.5          3.5          1.3          0.2
setosa            4.9          3.1          1.5          0.1
setosa            4.4          3.0          1.3          0.2
setosa            5.1          3.4          1.5          0.2
setosa            5.0          3.5          1.3          0.3
setosa            4.5          2.3          1.3          0.3
setosa            4.4          3.2          1.3          0.2
setosa            5.0          3.5          1.6          0.6
setosa            5.1          3.8          1.9          0.4
setosa            4.8          3.0          1.4          0.3
setosa            5.1          3.8          1.6          0.2
setosa            4.6          3.2          1.4          0.2
setosa            5.3          3.7          1.5          0.2
setosa            5.0          3.3          1.4          0.2
Tokenization took: 0.06 ms
Type conversion took: 0.25 ms
Parser memory cleanup took: 0.00 ms
            sepal_length  sepal_width petal_length  petal_width
species
versicolor           7.0          3.2          4.7          1.4
versicolor           6.4          3.2          4.5          1.5
versicolor           6.9          3.1          4.9          1.5
versicolor           5.5          2.3          4.0          1.3
versicolor           6.5          2.8          4.6          1.5
versicolor           5.7          2.8          4.5          1.3
versicolor           6.3          3.3          4.7          1.6
versicolor           4.9          2.4          3.3          1.0
versicolor           6.6          2.9          4.6          1.3
versicolor           5.2          2.7          3.9          1.4
versicolor           5.0          2.0          3.5          1.0
versicolor           5.9          3.0          4.2          1.5
versicolor           6.0          2.2          4.0          1.0
versicolor           6.1          2.9          4.7          1.4
versicolor           5.6          2.9          3.6          1.3
versicolor           6.7          3.1          4.4          1.4
versicolor           5.6          3.0          4.5          1.5
versicolor           5.8          2.7          4.1          1.0
versicolor           6.2          2.2          4.5          1.5
versicolor           5.6          2.5          3.9          1.1
versicolor           5.9          3.2          4.8          1.8
versicolor           6.1          2.8          4.0          1.3
versicolor           6.3          2.5          4.9          1.5
versicolor           6.1          2.8          4.7          1.2
versicolor           6.4          2.9          4.3          1.3
versicolor           6.6          3.0          4.4          1.4
versicolor           6.8          2.8          4.8          1.4
versicolor           6.7          3.0          5.0          1.7
versicolor           6.0          2.9          4.5          1.5
versicolor           5.7          2.6          3.5          1.0
versicolor           5.5          2.4          3.8          1.1
versicolor           5.5          2.4          3.7          1.0
versicolor           5.8          2.7          3.9          1.2
versicolor           6.0          2.7          5.1          1.6
versicolor           5.4          3.0          4.5          1.5
versicolor           6.0          3.4          4.5          1.6
versicolor           6.7          3.1          4.7          1.5
versicolor           6.3          2.3          4.4          1.3
versicolor           5.6          3.0          4.1          1.3
versicolor           5.5          2.5          4.0          1.3
versicolor           5.5          2.6          4.4          1.2
versicolor           6.1          3.0          4.6          1.4
versicolor           5.8          2.6          4.0          1.2
versicolor           5.0          2.3          3.3          1.0
versicolor           5.6          2.7          4.2          1.3
versicolor           5.7          3.0          4.2          1.2
versicolor           5.7          2.9          4.2          1.3
versicolor           6.2          2.9          4.3          1.3
versicolor           5.1          2.5          3.0          1.1
versicolor           5.7          2.8          4.1          1.3
Tokenization took: 0.34 ms
Type conversion took: 0.24 ms
Parser memory cleanup took: 0.00 ms
           sepal_length  sepal_width petal_length  petal_width
species
virginica           6.3          3.3          6.0          2.5
virginica           5.8          2.7          5.1          1.9
virginica           7.1          3.0          5.9          2.1
virginica           6.3          2.9          5.6          1.8
virginica           6.5          3.0          5.8          2.2
virginica           7.6          3.0          6.6          2.1
virginica           4.9          2.5          4.5          1.7
virginica           7.3          2.9          6.3          1.8
virginica           6.7          2.5          5.8          1.8
virginica           7.2          3.6          6.1          2.5
virginica           6.5          3.2          5.1          2.0
virginica           6.4          2.7          5.3          1.9
virginica           6.8          3.0          5.5          2.1
virginica           5.7          2.5          5.0          2.0
virginica           5.8          2.8          5.1          2.4
virginica           6.4          3.2          5.3          2.3
virginica           6.5          3.0          5.5          1.8
virginica           7.7          3.8          6.7          2.2
virginica           7.7          2.6          6.9          2.3
virginica           6.0          2.2          5.0          1.5
virginica           6.9          3.2          5.7          2.3
virginica           5.6          2.8          4.9          2.0
virginica           7.7          2.8          6.7          2.0
virginica           6.3          2.7          4.9          1.8
virginica           6.7          3.3          5.7          2.1
virginica           7.2          3.2          6.0          1.8
virginica           6.2          2.8          4.8          1.8
virginica           6.1          3.0          4.9          1.8
virginica           6.4          2.8          5.6          2.1
virginica           7.2          3.0          5.8          1.6
virginica           7.4          2.8          6.1          1.9
virginica           7.9          3.8          6.4          2.0
virginica           6.4          2.8          5.6          2.2
virginica           6.3          2.8          5.1          1.5
virginica           6.1          2.6          5.6          1.4
virginica           7.7          3.0          6.1          2.3
virginica           6.3          3.4          5.6          2.4
virginica           6.4          3.1          5.5          1.8
virginica           6.0          3.0          4.8          1.8
virginica           6.9          3.1          5.4          2.1
virginica           6.7          3.1          5.6          2.4
virginica           6.9          3.1          5.1          2.3
virginica           5.8          2.7          5.1          1.9
virginica           6.8          3.2          5.9          2.3
virginica           6.7          3.3          5.7          2.5
virginica           6.7          3.0          5.2          2.3
virginica           6.3          2.5          5.0          1.9
virginica           6.5          3.0          5.2          2.0
virginica           6.2          3.4          5.4          2.3
virginica           5.9          3.0          5.1          1.8

In [343]:
data.get_chunk(50)

Tokenization took: 0.13 ms
Type conversion took: 0.37 ms
Parser memory cleanup took: 0.00 ms

            sepal_length  sepal_width petal_length  petal_width
species
versicolor           7.0          3.2          4.7          1.4
versicolor           6.4          3.2          4.5          1.5
versicolor           6.9          3.1          4.9          1.5
versicolor           5.5          2.3          4.0          1.3
versicolor           6.5          2.8          4.6          1.5
versicolor           5.7          2.8          4.5          1.3
versicolor           6.3          3.3          4.7          1.6
versicolor           4.9          2.4          3.3          1.0
versicolor           6.6          2.9          4.6          1.3
versicolor           5.2          2.7          3.9          1.4
versicolor           5.0          2.0          3.5          1.0
versicolor           5.9          3.0          4.2          1.5
versicolor           6.0          2.2          4.0          1.0
versicolor           6.1          2.9          4.7          1.4
versicolor           5.6          2.9          3.6          1.3
versicolor           6.7          3.1          4.4          1.4
versicolor           5.6          3.0          4.5          1.5
versicolor           5.8          2.7          4.1          1.0
versicolor           6.2          2.2          4.5          1.5
versicolor           5.6          2.5          3.9          1.1
versicolor           5.9          3.2          4.8          1.8
versicolor           6.1          2.8          4.0          1.3
versicolor           6.3          2.5          4.9          1.5
versicolor           6.1          2.8          4.7          1.2
versicolor           6.4          2.9          4.3          1.3
versicolor           6.6          3.0          4.4          1.4
versicolor           6.8          2.8          4.8          1.4
versicolor           6.7          3.0          5.0          1.7
versicolor           6.0          2.9          4.5          1.5
versicolor           5.7          2.6          3.5          1.0
versicolor           5.5          2.4          3.8          1.1
versicolor           5.5          2.4          3.7          1.0
versicolor           5.8          2.7          3.9          1.2
versicolor           6.0          2.7          5.1          1.6
versicolor           5.4          3.0          4.5          1.5
versicolor           6.0          3.4          4.5          1.6
versicolor           6.7          3.1          4.7          1.5
versicolor           6.3          2.3          4.4          1.3
versicolor           5.6          3.0          4.1          1.3
versicolor           5.5          2.5          4.0          1.3
versicolor           5.5          2.6          4.4          1.2
versicolor           6.1          3.0          4.6          1.4
versicolor           5.8          2.6          4.0          1.2
versicolor           5.0          2.3          3.3          1.0
versicolor           5.6          2.7          4.2          1.3
versicolor           5.7          3.0          4.2          1.2
versicolor           5.7          2.9          4.2          1.3
versicolor           6.2          2.9          4.3          1.3
versicolor           5.1          2.5          3.0          1.1
versicolor           5.7          2.8          4.1          1.3

In [347]:
pd.read_csv("/Users/bhuwankarki/Desktop/DS-ML-2021-04/Data/house_rental_data.csv.txt",
           usecols=lambda x:x.startswith("B")).head()

   Bedroom  Bathroom
0        2         2
1        4         2
2        2         1
3        3         2
4        3         2

In [350]:
df=pd.read_csv("../Data/sales-data.csv")

In [354]:
li=df["Month"].to_list()

In [356]:
import datetime

In [359]:
for i in li:
    print(datetime.datetime.strptime("200"+i,"%Y-%m"))

2001-01-01 00:00:00
2001-02-01 00:00:00
2001-03-01 00:00:00
2001-04-01 00:00:00
2001-05-01 00:00:00
2001-06-01 00:00:00
2001-07-01 00:00:00
2001-08-01 00:00:00
2001-09-01 00:00:00
2001-10-01 00:00:00
2001-11-01 00:00:00
2001-12-01 00:00:00
2002-01-01 00:00:00
2002-02-01 00:00:00
2002-03-01 00:00:00
2002-04-01 00:00:00
2002-05-01 00:00:00
2002-06-01 00:00:00
2002-07-01 00:00:00
2002-08-01 00:00:00
2002-09-01 00:00:00
2002-10-01 00:00:00
2002-11-01 00:00:00
2002-12-01 00:00:00
2003-01-01 00:00:00
2003-02-01 00:00:00
2003-03-01 00:00:00
2003-04-01 00:00:00
2003-05-01 00:00:00
2003-06-01 00:00:00
2003-07-01 00:00:00
2003-08-01 00:00:00
2003-09-01 00:00:00
2003-10-01 00:00:00
2003-11-01 00:00:00
2003-12-01 00:00:00

   Month  Sales
0   1-01  266.0
1   1-02  145.9
2   1-03  183.1
3   1-04  119.3
4   1-05  180.3
5   1-06  168.5
6   1-07  231.8
7   1-08  224.5
8   1-09  192.8
9   1-10  122.9
10  1-11  336.5
11  1-12  185.9
12  2-01  194.3
13  2-02  149.5
14  2-03  210.1
15  2-04  273.3
16  2-05  191.4
17  2-06  287.0
18  2-07  226.0
19  2-08  303.6
20  2-09  289.9
21  2-10  421.6
22  2-11  264.5
23  2-12  342.3
24  3-01  339.7
25  3-02  440.4
26  3-03  315.9
27  3-04  439.3
28  3-05  401.3
29  3-06  437.4
30  3-07  575.5
31  3-08  407.6
32  3-09  682.0
33  3-10  475.3
34  3-11  581.3
35  3-12  646.9

In [363]:
pd.read_csv("../Data/sales-data.csv",parse_dates=["Month"],date_parser=lambda x: (datetime.datetime.strptime("200"+x,"%Y-%m")))

        Month  Sales
0  2001-01-01  266.0
1  2001-02-01  145.9
2  2001-03-01  183.1
3  2001-04-01  119.3
4  2001-05-01  180.3
5  2001-06-01  168.5
6  2001-07-01  231.8
7  2001-08-01  224.5
8  2001-09-01  192.8
9  2001-10-01  122.9
10 2001-11-01  336.5
11 2001-12-01  185.9
12 2002-01-01  194.3
13 2002-02-01  149.5
14 2002-03-01  210.1
15 2002-04-01  273.3
16 2002-05-01  191.4
17 2002-06-01  287.0
18 2002-07-01  226.0
19 2002-08-01  303.6
20 2002-09-01  289.9
21 2002-10-01  421.6
22 2002-11-01  264.5
23 2002-12-01  342.3
24 2003-01-01  339.7
25 2003-02-01  440.4
26 2003-03-01  315.9
27 2003-04-01  439.3
28 2003-05-01  401.3
29 2003-06-01  437.4
30 2003-07-01  575.5
31 2003-08-01  407.6
32 2003-09-01  682.0
33 2003-10-01  475.3
34 2003-11-01  581.3
35 2003-12-01  646.9

In [365]:
pd.read_csv("/Users/bhuwankarki/Desktop/DS-ML-2021-04/Data/house_rental_data.csv.txt",
   index_col="Unnamed: 0").head()

       Sqft  Floor  TotalFloor  Bedroom  Living.Room  Bathroom  Price
1  1177.698      2           7        2            2         2  62000
2  2134.800      5           7        4            2         2  78000
3  1138.560      5           7        2            2         1  58000
4  1458.780      2           7        3            2         2  45000
5   967.776     11          14        3            2         2  45000

In [371]:
pd.read_csv("../Data/titanic-train.csv.txt")

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [385]:
pd.read_csv("../Data/titanic-train.csv.txt",converters={"Cabin":lambda x:1})

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,1,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,1,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,1,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,1,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,1,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,1,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,1,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,1,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,1,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,1,Q

### loading json file

In [386]:
url="https://raw.githubusercontent.com/cheprasov/json-colors/master/colors.json"

In [388]:
pd.read_json(url)

                   name      hex
0         Absolute Zero  #0048BA
1            Acid Green  #B0BF1A
2                  Aero  #7CB9E8
3             Aero Blue  #C9FFE5
4        African Violet  #B284BE
...                 ...      ...
1297        Yellow Rose  #FFF000
1298    Yellow Sunshine  #FFF700
1299             Zaffre  #0014A8
1300  Zinnwaldite Brown  #2C1608
1301               Zomp  #39A78E

[1302 rows x 2 columns]

In [394]:
df=pd.read_json("https://sampo.thl.fi/pivot/prod/en/epirapo/covid19case/fact_epirapo_covid19case.json?column=ttr10yage-444309")

In [406]:
data = [{'state': 'Florida',
...          'shortname': 'FL',
...          'info': {'governor': 'Rick Scott'},
...          'counties': [{'name': 'Dade', 'population': 12345},
...                       {'name': 'Broward', 'population': 40000},
...                       {'name': 'Palm Beach', 'population': 60000}]},
...         {'state': 'Ohio',
...          'shortname': 'OH',
...          'info': {'governor': 'John Kasich'},
...          'counties': [{'name': 'Summit', 'population': 1234},
...                       {'name': 'Cuyahoga', 'population': 1337}]}]

In [407]:
data

[{'state': 'Florida',
  'shortname': 'FL',
  'info': {'governor': 'Rick Scott'},
  'counties': [{'name': 'Dade', 'population': 12345},
   {'name': 'Broward', 'population': 40000},
   {'name': 'Palm Beach', 'population': 60000}]},
 {'state': 'Ohio',
  'shortname': 'OH',
  'info': {'governor': 'John Kasich'},
  'counties': [{'name': 'Summit', 'population': 1234},
   {'name': 'Cuyahoga', 'population': 1337}]}]

In [416]:
pd.json_normalize(data)

,state,shortname,counties,info.governor
0,Florida,FL,"[{'name': 'Dade', 'population': 12345}, {'name...",Rick Scott
1,Ohio,OH,"[{'name': 'Summit', 'population': 1234}, {'nam...",John Kasich

In [417]:
pd.json_normalize(data=data, record_path='counties')

         name  population
0        Dade       12345
1     Broward       40000
2  Palm Beach       60000
3      Summit        1234
4    Cuyahoga        1337

In [424]:
pd.json_normalize(data=data, record_path='counties',meta=["state","shortname",["info","governor"]])

         name  population    state shortname info.governor
0        Dade       12345  Florida        FL    Rick Scott
1     Broward       40000  Florida        FL    Rick Scott
2  Palm Beach       60000  Florida        FL    Rick Scott
3      Summit        1234     Ohio        OH   John Kasich
4    Cuyahoga        1337     Ohio        OH   John Kasich

## loding excel

In [426]:
pd.read_excel("../Data/HealthCareData-1.xlsx")

,S.NO,Age,Gender,Place(location where the patient lives),Duration of alcohol consumption(years),Quantity of alcohol consumption (quarters/day),Type of alcohol consumed,Hepatitis B infection,Hepatitis C infection,Diabetes Result,...,Indirect (mg/dl),Total Protein (g/dl),Albumin (g/dl),Globulin (g/dl),A/G Ratio,AL.Phosphatase (U/L),SGOT/AST (U/L),SGPT/ALT (U/L),USG Abdomen (diffuse liver or not),Predicted Value(Out Come-Patient suffering from liver cirrosis or not)
0,1,55,male,rural,12,2,branded liquor,negative,negative,YES,...,3.0,6.0,3.0,4.0,0.75,150.0,56,34,YES,YES
1,2,55,male,rural,12,2,branded liquor,negative,negative,YES,...,3.0,6.0,3.0,4.0,0.75,150.0,56,34,YES,YES
2,3,55,male,rural,12,2,branded liquor,negative,negative,YES,...,3.0,6.0,3.0,4.0,0.75,150.0,56,34,YES,YES
3,4,55,male,rural,12,2,branded liquor,negative,negative,NO,...,3.0,6.0,3.0,4.0,0.75,150.0,56,34,YES,YES
4,5,55,female,rural,12,2,branded liquor,negative,negative,YES,...,3.0,6.0,3.0,4.0,0.75,150.0,56,34,YES,YES
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
945,946,54,female,rural,5,3,country liquor,negative,negative,NO,...,2.0,5.4,5.2,3.4,NaN,86.0,110,70,no,no
946,947,72,female,urban,4,3,branded liquor,negative,negative,NO,...,2.0,5.3,4.2,3.5,NaN,110.0,110,70,no,no
947,948,47,male,urban,7,3,country liquor,Positive,Positive,NO,...,2.0,6.4,4.2,2.5,1.68,90.0,110,70,no,no
948,949,54,female,rural,9,3,country liquor,Positive,Positive,NO,...,2.0,5.9,4.2,2.5,1.8,110.0,110,70,no,no
949,950,52,male,rural,8,3,country liquor,Positive,Positive,NO,...,2.0,7.1,4.2,2.5,1.8,56.0,110,70,no,no

In [429]:
pd.read_excel("../Data/sales-funnel.xlsx",sheet_name="Sheet2")

,gsdadg,Unnamed: 1,Unnamed: 2,Unnamed: 3,gdag,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,gsa
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,gdsa,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,dsagdsea,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## loading from the database

In [448]:
import sqlite3
conn=sqlite3.connect("../Data/database.sqlite")

In [449]:
conn.execute("SELECT * FROM Company where Address=='Texas' ").fetchall()

[(2, 'Allen', 25, 'Texas', 15000.0)]

In [437]:
pd.read_sql_query("SELECT * FROM Company ",conn)

   ID   NAME  AGE     ADDRESS   SALARY
0   1   Paul   32  California  20000.0
1   2  Allen   25       Texas  15000.0
2   3  Teddy   23      Norway  20000.0
3   4   Mark   25  Rich-Mond   65000.0

In [464]:
df=pd.read_sql("SELECT * FROM Company ",conn)

In [441]:
#pd.read_sql_table("Company",conn)

In [458]:
df.to_json("file.json")

In [452]:
df[df.ADDRESS=="Texas"]

   ID   NAME  AGE ADDRESS   SALARY
1   2  Allen   25   Texas  15000.0

In [454]:
pd.read_sql("SELECT * FROM Company where name='Paul' ",conn)

   ID  NAME  AGE     ADDRESS   SALARY
0   1  Paul   32  California  20000.0

## pickle

In [459]:
import pickle

#Here's an example dict
grades = { 'Alice': 89, 'Bob': 72, 'Charles': 87 }

#Use dumps to convert the object to a serialized string
serial_grades = pickle.dumps( grades )

#Use loads to de-serialize an object
received_grades = pickle.loads( serial_grades )

In [461]:
serial_grades

b'\x80\x04\x95#\x00\x00\x00\x00\x00\x00\x00}\x94(\x8c\x05Alice\x94KY\x8c\x03Bob\x94KH\x8c\x07Charles\x94KWu.'

In [462]:
received_grades

{'Alice': 89, 'Bob': 72, 'Charles': 87}

In [465]:
pd.to_pickle(df,"pick.pkl")

In [466]:
pd.read_pickle("pick.pkl")

   ID   NAME  AGE     ADDRESS   SALARY
0   1   Paul   32  California  20000.0
1   2  Allen   25       Texas  15000.0
2   3  Teddy   23      Norway  20000.0
3   4   Mark   25  Rich-Mond   65000.0

In [467]:
url="https://w3qa5ydb4l.execute-api.eu-west-1.amazonaws.com/prod/finnishCoronaData"

In [471]:
import json
import requests

In [474]:
data=requests.get(url).content

In [476]:
json_data=json.loads(data)

In [479]:
json_data["confirmed"]

[{'id': '1',
  'date': '2020-01-29T11:00:00.000Z',
  'healthCareDistrict': 'Lappi',
  'infectionSourceCountry': 'CHN',
  'infectionSource': 'unknown'},
 {'id': '2',
  'date': '2020-02-26T11:00:00.000Z',
  'healthCareDistrict': 'HUS',
  'infectionSourceCountry': 'ITA',
  'infectionSource': 'unknown'},
 {'id': '3',
  'date': '2020-03-01T11:00:00.000Z',
  'healthCareDistrict': 'HUS',
  'infectionSourceCountry': 'FIN',
  'infectionSource': 2},
 {'id': '4',
  'date': '2020-02-28T11:00:00.000Z',
  'healthCareDistrict': 'HUS',
  'infectionSourceCountry': 'ITA',
  'infectionSource': 'unknown'},
 {'id': '5',
  'date': '2020-03-01T11:00:00.000Z',
  'healthCareDistrict': 'HUS',
  'infectionSourceCountry': 'FIN',
  'infectionSource': 4},
 {'id': '6',
  'date': '2020-03-01T11:00:00.000Z',
  'healthCareDistrict': 'HUS',
  'infectionSourceCountry': 'FIN',
  'infectionSource': 4},
 {'id': '7',
  'date': '2020-03-02T11:00:00.000Z',
  'healthCareDistrict': 'HUS',
  'infectionSourceCountry': 'FIN',
  'infectionSource': 4},
 {'id': '8',
  'date': '2020-03-05T09:00:00.000Z',
  'healthCareDistrict': 'Kanta-Häme',
  'infectionSourceCountry': 'ITA',
  'infectionSource': 'unknown'},
 {'id': '9',
  'date': '2020-03-05T09:00:00.000Z',
  'healthCareDistrict': 'Pirkanmaa',
  'infectionSourceCountry': 'ITA',
  'infectionSource': 'unknown'},
 {'id': '10',
  'date': '2020-03-05T09:00:00.000Z',
  'healthCareDistrict': 'HUS',
  'infectionSourceCountry': 'FIN',
  'infectionSource': 'related to earlier'},
 {'id': '11',
  'date': '2020-03-05T09:00:00.000Z',
  'healthCareDistrict': 'HUS',
  'infectionSourceCountry': 'ITA',
  'infectionSource': 'unknown'},
 {'id': '12',
  'date': '2020-03-05T09:00:00.000Z',
  'healthCareDistrict': 'HUS',
  'infectionSourceCountry': 'ITA',
  'infectionSource': 'unknown'},
 {'id': '13',
  'date': '2020-03-06T08:50:00.000Z',
  'healthCareDistrict': 'HUS',
  'infectionSourceCountry': 'ITA',
  'infectionSource': 'unknown'},
 {'id': '14',
  'date': '2020-03-06T08:50:00.000Z',
  'healthCareDistrict': 'Etelä-Karjala',
  'infectionSourceCountry': 'ITA',
  'infectionSource': 'unknown'},
 {'id': '15',
  'date': '2020-03-06T08:50:00.000Z',
  'healthCareDistrict': 'Pohjois-Pohjanmaa',
  'infectionSourceCountry': 'IRN',
  'infectionSource': 'unknown'},
 {'id': '16',
  'date': '2020-03-07T08:50:00.000Z',
  'healthCareDistrict': 'Pirkanmaa',
  'infectionSourceCountry': 'ITA',
  'infectionSource': 'unknown'},
 {'id': '17',
  'date': '2020-03-07T08:50:00.000Z',
  'healthCareDistrict': 'Pirkanmaa',
  'infectionSourceCountry': 'ITA',
  'infectionSource': 'unknown'},
 {'id': '18',
  'date': '2020-03-07T08:50:00.000Z',
  'healthCareDistrict': 'HUS',
  'infectionSourceCountry': 'ITA',
  'infectionSource': 'unknown'},
 {'id': '19',
  'date': '2020-03-07T08:50:00.000Z',
  'healthCareDistrict': 'HUS',
  'infectionSourceCountry': 'ITA',
  'infectionSource': 'unknown'},
 {'id': '20',
  'date': '2020-03-08T08:30:00.000Z',
  'healthCareDistrict': None,
  'infectionSourceCountry': '',
  'infectionSource': 'unknown'},
 {'id': '21',
  'date': '2020-03-08T08:50:00.000Z',
  'healthCareDistrict': 'HUS',
  'infectionSourceCountry': 'ITA',
  'infectionSource': 'unknown'},
 {'id': '22',
  'date': '2020-03-08T08:50:00.000Z',
  'healthCareDistrict': 'HUS',
  'infectionSourceCountry': 'FIN',
  'infectionSource': 21},
 {'id': '23',
  'date': '2020-03-08T09:00:00.000Z',
  'healthCareDistrict': 'Pohjois-Savo',
  'infectionSourceCountry': 'ITA',
  'infectionSource': 'unknown'},
 {'id': '24',
  'date': '2020-03-08T15:45:00.000Z',
  'healthCareDistrict': 'Varsinais-Suomi',
  'infectionSourceCountry': 'ITA',
  'infectionSource': 'unknown'},
 {'id': '25',
  'date': '2020-03-09T09:00:00.000Z',
  'healthCareDistrict': 'HUS',
  'infectionSourceCountry': 'ITA',
  'infectionSource': 'unknown'},
 {'id': '26',
  'date': '2020-03-09T09:00:00.000Z',
  'healthCareDistrict': 'HUS',
  'infectionSourceCountry': 'ITA',
  'infectionSource': 'unknown'},
 {'id': '27',
  'date': '2020-03-09T09:00:00.000Z',
  'healthCareDistrict': 'HUS',
  'infectionSourceCountry': 'FIN',
  'infectionSource': 'related to earlier'},
 {'id': '28',
  'date': '2020-03-09T09:00:00.000Z',
  'healthCareDistrict': 'HUS',
  'infectionSourceCountry': 'FIN',
  'infectionSource': 'related to earlier'},
 {'id': '29',
  'date': '2020-03-09T09:00:00.000Z',
  'healthCareDistrict': 'Pirkanmaa',
  'infectionSourceCountry': 'ITA',
  'infectionSource': 'unknown'},
 {'id': '30',
  'date': '2020-03-09T09:00:00.000Z',
  'healthCareDistrict': 'Kanta-Häme',
  'infectionSourceCountry': 'ITA',
  'infectionSource': 'unknown'},
 {'id': '31',
  'date': '2020-03-09T13:00:00.000Z',
  'healthCareDistrict': 'Keski-Suomi',
  'infectionSourceCountry': 'ITA',
  'infectionSource': 'unknown'},
 {'id': '32',
  'date': '2020-03-09T13:00:00.000Z',
  'healthCareDistrict': 'Keski-Suomi',
  'infectionSourceCountry': 'FIN',
  'infectionSource': 31},
 {'id': '33',
  'date': '2020-03-09T13:00:00.000Z',
  'healthCareDistrict': 'Keski-Suomi',
  'infectionSourceCountry': 'FIN',
  'infectionSource': 31},
 {'id': '34',
  'date': '2020-03-10T07:15:00.000Z',
  'healthCareDistrict': 'Pohjois-Savo',
  'infectionSourceCountry': 'ITA',
  'infectionSource': 'unknown'},
 {'id': '35',
  'date': '2020-03-10T08:30:00.000Z',
  'healthCareDistrict': 'HUS',
  'infectionSourceCountry': 'ITA',
  'infectionSource': 'unknown'},
 {'id': '36',
  'date': '2020-03-10T08:30:00.000Z',
  'healthCareDistrict': 'HUS',
  'infectionSourceCountry': 'ITA',
  'infectionSource': 'unknown'},
 {'id': '37',
  'date': '2020-03-10T08:30:00.000Z',
  'healthCareDistrict': 'HUS',
  'infectionSourceCountry': 'FIN',
  'infectionSource': 'unknown'},
 {'id': '38',
  'date': '2020-03-10T08:30:00.000Z',
  'healthCareDistrict': 'Pohjois-Karjala',
  'infectionSourceCountry': 'ITA',
  'infectionSource': 'unknown'},
 {'id': '39',
  'date': '2020-03-10T10:30:00.000Z',
  'healthCareDistrict': 'Varsinais-Suomi',
  'infectionSourceCountry': 'ITA',
  'infectionSource': 'unknown'},
 {'id': '40',
  'date': '2020-03-10T10:30:00.000Z',
  'healthCareDistrict': 'Kanta-Häme',
  'infectionSourceCountry': 'ITA',
  'infectionSource': 'unknown'},
 {'id': '41',
  'date': '2020-03-11T09:00:00.000Z',
  'healthCareDistrict': 'Pirkanmaa',
  'infectionSourceCountry': 'ITA',
  'infectionSource': 'unknown'},
 {'id': '42',
  'date': '2020-03-11T09:00:00.000Z',
  'healthCareDistrict': 'Pirkanmaa',
  'infectionSourceCountry': 'ITA',
  'infectionSource': 'unknown'},
 {'id': '43',
  'date': '2020-03-11T09:00:00.000Z',
  'healthCareDistrict': 'Pirkanmaa',
  'infectionSourceCountry': 'FIN',
  'infectionSource': 16},
 {'id': '44',
  'date': '2020-03-11T09:00:00.000Z',
  'healthCareDistrict': 'Kanta-Häme',
  'infectionSourceCountry': 'FIN',
  'infectionSource': 30},
 {'id': '45',
  'date': '2020-03-11T09:00:00.000Z',
  'healthCareDistrict': 'Varsinais-Suomi',
  'infectionSourceCountry': 'AUT',
  'infectionSource': 'unknown'},
 {'id': '46',
  'date': '2020-03-11T09:15:00.000Z',
  'healthCareDistrict': 'HUS',
  'infectionSourceCountry': '',
  'infectionSource': 'unknown'},
 {'id': '47',
  'date': '2020-03-11T09:15:00.000Z',
  'healthCareDistrict': 'HUS',
  'infectionSourceCountry': '',
  'infectionSource': 'unknown'},
 {'id': '48',
  'date': '2020-03-11T09:15:00.000Z',
  'healthCareDistrict': 'HUS',
  'infectionSourceCountry': '',
  'infectionSource': 'unknown'},
 {'id': '49',
  'date': '2020-03-11T09:15:00.000Z',
  'healthCareDistrict': 'HUS',
  'infectionSourceCountry': '',
  'infectionSource': 'unknown'},
 {'id': '50',
  'date': '2020-03-11T09:15:00.000Z',
  'healthCareDistrict': 'HUS',
  'infectionSourceCountry': '',
  'infectionSource': 'unknown'},
 {'id': '51',
  'date': '2020-03-11T09:15:00.000Z',
  'healthCareDistrict': 'HUS',
  'infectionSourceCountry': '',
  'infectionSource': 'unknown'},
 {'id': '52',
  'date': '2020-03-11T09:15:00.000Z',
  'healthCareDistrict': 'HUS',
  'infectionSourceCountry': '',
  'infectionSource': 'unknown'},
 {'id': '53',
  'date': '2020-03-11T09:15:00.000Z',
  'healthCareDistrict': 'HUS',
  'infectionSourceCountry': '',
  'infectionSource': 'unknown'},
 {'id': '54',
  'date': '2020-03-11T09:15:00.000Z',
  'healthCareDistrict': 'HUS',
  'infectionSourceCountry': '',
  'infectionSource': 'unknown'},
 {'id': '55',
  'date': '2020-03-11T09:15:00.000Z',
  'healthCareDistrict': 'HUS',
  'infectionSourceCountry': '',
  'infectionSource': 'unknown'},
 {'id': '56',
  'date': '2020-03-11T09:15:00.000Z',
  'healthCareDistrict': 'HUS',
  'infectionSourceCountry': '',
  'infectionSource': 'unknown'},
 {'id': '57',
  'date': '2020-03-11T09:20:00.000Z',
  'healthCareDistrict': 'Keski-Suomi',
  'infectionSourceCountry': 'ITA',
  'infectionSource': 'unknown'},
 {'id': '58',
  'date': '2020-03-11T10:55:00.000Z',
  'healthCareDistrict': 'Etelä-Karjala',
  'infectionSourceCountry': 'FIN',
  'infectionSource': 'unknown'},
 {'id': '59',
  'date': '2020-03-11T11:45:00.000Z',
  'healthCareDistrict': 'Etelä-Pohjanmaa',
  'infectionSourceCountry': 'ITA',
  'infectionSource': 'unknown'},
 {'id': '61',
  'date': '2020-03-11T17:00:00.000Z',
  'healthCareDistrict': 'Satakunta',
  'infectionSourceCountry': 'AUT',
  'infectionSource': 'unknown'},
 {'id': '62',
  'date': '2020-03-11T17:00:00.000Z',
  'healthCareDistrict': 'Satakunta',
  'infectionSourceCountry': 'AUT',
  'infectionSource': 'unknown'},
 {'id': '63',
  'date': '2020-03-11T20:00:00.000Z',
  'healthCareDistrict': 'Kanta-Häme',
  'infectionSourceCountry': 'FIN',
  'infectionSource': 44},
 {'id': '64',
  'date': '2020-03-11T20:00:00.000Z',
  'healthCareDistrict': 'Kanta-Häme',
  'infectionSourceCountry': 'FIN',
  'infectionSource': 44},
 {'id': '65',
  'date': '2020-03-11T20:00:00.000Z',
  'healthCareDistrict': 'Kanta-Häme',
  'infectionSourceCountry': 'FIN',
  'infectionSource': 'unknown'},
 {'id': '66',
  'date': '2020-03-11T20:00:00.000Z',
  'healthCareDistrict': 'Kanta-Häme',
  'infectionSourceCountry': 'FIN',
  'infectionSource': 'unknown'},
 {'id': '67',
  'date': '2020-03-12T08:35:00.000Z',
  'healthCareDistrict': 'HUS',
  'infectionSourceCountry': '',
  'infectionSource': 'unknown'},
 {'id': '68',
  'date': '2020-03-12T08:35:00.000Z',
  'healthCareDistrict': 'HUS',
  'infectionSourceCountry': '',
  'infectionSource': 'unknown'},
 {'id': '69',
  'date': '2020-03-12T08:35:00.000Z',
  'healthCareDistrict': 'HUS',
  'infectionSourceCountry': '',
  'infectionSource': 'unknown'},
 {'id': '70',
  'date': '2020-03-12T08:35:00.000Z',
  'healthCareDistrict': 'HUS',
  'infectionSourceCountry': '',
  'infectionSource': 'unknown'},
 {'id': '71',
  'date': '2020-03-12T08:35:00.000Z',
  'healthCareDistrict': 'HUS',
  'infectionSourceCountry': '',
  'infectionSource': 'unknown'},
 {'id': '72',
  'date': '2020-03-12T08:35:00.000Z',
  'healthCareDistrict': 'HUS',
  'infectionSourceCountry': '',
  'infectionSource': 'unknown'},
 {'id': '73',
  'date': '2020-03-12T08:35:00.000Z',
  'healthCareDistrict': 'HUS',
  'infectionSourceCountry': '',
  'infectionSource': 'unknown'},
 {'id': '74',
  'date': '2020-03-12T08:35:00.000Z',
  'healthCareDistrict': 'HUS',
  'infectionSourceCountry': '',
  'infectionSource': 'unknown'},
 {'id': '75',
  'date': '2020-03-12T08:35:00.000Z',
  'healthCareDistrict': 'HUS',
  'infectionSourceCountry': '',
  'infectionSource': 'unknown'},
 {'id': '76',
  'date': '2020-03-12T08:35:00.000Z',
  'healthCareDistrict': 'HUS',
  'infectionSourceCountry': '',
  'infectionSource': 'unknown'},
 {'id': '77',
  'date': '2020-03-12T08:35:00.000Z',
  'healthCareDistrict': 'HUS',
  'infectionSourceCountry': '',
  'infectionSource': 'unknown'},
 {'id': '78',
  'date': '2020-03-12T08:35:00.000Z',
  'healthCareDistrict': 'HUS',
  'infectionSourceCountry': '',
  'infectionSource': 'unknown'},
 {'id': '79',
  'date': '2020-03-12T08:35:00.000Z',
  'healthCareDistrict': 'HUS',
  'infectionSourceCountry': '',
  'infectionSource': 'unknown'},
 {'id': '80',
  'date': '2020-03-12T08:35:00.000Z',
  'healthCareDistrict': 'HUS',
  'infectionSourceCountry': '',
  'infectionSource': 'unknown'},
 {'id': '81',
  'date': '2020-03-12T08:45:00.000Z',
  'healthCareDistrict': 'Pirkanmaa',
  'infectionSourceCountry': 'AUT',
  'infectionSource': 'unknown'},
 {'id': '82',
  'date': '2020-03-12T08:45:00.000Z',
  'healthCareDistrict': 'Pirkanmaa',
  'infectionSourceCountry': 'AUT',
  'infectionSource': 'unknown'},
 {'id': '83',
  'date': '2020-03-12T08:45:00.000Z',
  'healthCareDistrict': 'Pirkanmaa',
  'infectionSourceCountry': 'AUT',
  'infectionSource': 'unknown'},
 {'id': '84',
  'date': '2020-03-12T08:45:00.000Z',
  'healthCareDistrict': 'Pirkanmaa',
  'infectionSourceCountry': 'AUT',
  'infectionSource': 'unknown'},
 {'id': '85',
  'date': '2020-03-12T09:15:00.000Z',
  'healthCareDistrict': 'Varsinais-Suomi',
  'infectionSourceCountry': 'FIN',
  'infectionSource': 39},
 {'id': '86',
  'date': '2020-03-12T09:15:00.000Z',
  'healthCareDistrict': 'Varsinais-Suomi',
  'infectionSourceCountry': 'AUT',
  'infectionSource': 'unknown'},
 {'id': '87',
  'date': '2020-03-12T09:15:00.000Z',
  'healthCareDistrict': 'Keski-Suomi',
  'infectionSourceCountry': 'FIN',
  'infectionSource': 'unknown'},
 {'id': '88',
  'date': '2020-03-12T11:45:00.000Z',
  'healthCareDistrict': 'HUS',
  'infectionSourceCountry': '',
  'infectionSource': 'unknown'},
 {'id': '89',
  'date': '2020-03-12T11:45:00.000Z',
  'healthCareDistrict': 'HUS',
  'infectionSourceCountry': '',
  'infectionSource': 'unknown'},
 {'id': '90',
  'date': '2020-03-12T11:45:00.000Z',
  'healthCareDistrict': 'HUS',
  'infectionSourceCountry': '',
  'infectionSource': 'unknown'},
 {'id': '91',
  'date': '2020-03-12T11:45:00.000Z',
  'healthCareDistrict': 'HUS',
  'infectionSourceCountry': '',
  'infectionSource': 'unknown'},
 {'id': '92',
  'date': '2020-03-12T11:45:00.000Z',
  'healthCareDistrict': 'Pohjois-Pohjanmaa',
  'infectionSourceCountry': 'AUT',
  'infectionSource': 'unknown'},
 {'id': '93',
  'date': '2020-03-12T11:45:00.000Z',
  'healthCareDistrict': 'Pohjois-Pohjanmaa',
  'infectionSourceCountry': 'AUT',
  'infectionSource': 'unknown'},
 {'id': '94',
  'date': '2020-03-12T11:45:00.000Z',
  'healthCareDistrict': 'Pohjois-Pohjanmaa',
  'infectionSourceCountry': 'AUT',
  'infectionSource': 'unknown'},
 {'id': '95',
  'date': '2020-03-12T11:45:00.000Z',
  'healthCareDistrict': 'Pohjois-Pohjanmaa',
  'infectionSourceCountry': 'AUT',
  'infectionSource': 'unknown'},
 {'id': '96',
  'date': '2020-03-12T11:45:00.000Z',
  'healthCareDistrict': 'Pohjois-Pohjanmaa',
  'infectionSourceCountry': 'AUT',
  'infectionSource': 'unknown'},
 {'id': '97',
  'date': '2020-03-12T11:45:00.000Z',
  'healthCareDistrict': 'Pohjois-Pohjanmaa',
  'infectionSourceCountry': 'AUT',
  'infectionSource': 'unknown'},
 {'id': '98',
  'date': '2020-03-12T11:45:00.000Z',
  'healthCareDistrict': 'Pohjois-Pohjanmaa',
  'infectionSourceCountry': 'AUT',
  'infectionSource': 'unknown'},
 {'id': '99',
  'date': '2020-03-12T11:45:00.000Z',
  'healthCareDistrict': 'Pohjois-Pohjanmaa',
  'infectionSourceCountry': 'AUT',
  'infectionSource': 'unknown'},
 {'id': '100',
  'date': '2020-03-12T11:45:00.000Z',
  'healthCareDistrict': 'Pohjois-Pohjanmaa',
  'infectionSourceCountry': 'AUT',
  'infectionSource': 'unknown'},
 {'id': '101',
  'date': '2020-03-12T11:45:00.000Z',
  'healthCareDistrict': 'Pohjois-Pohjanmaa',
  'infectionSourceCountry': 'AUT',
  'infectionSource': 'unknown'},
 {'id': '102',
  'date': '2020-03-12T11:45:00.000Z',
  'healthCareDistrict': 'Pohjois-Pohjanmaa',
  'infectionSourceCountry': 'AUT',
  'infectionSource': 'unknown'},
 {'id': '103',
  'date': '2020-03-12T11:45:00.000Z',
  'healthCareDistrict': 'Pohjois-Pohjanmaa',
  'infectionSourceCountry': 'AUT',
  'infectionSource': 'unknown'},
 {'id': '104',
  'date': '2020-03-12T11:45:00.000Z',
  'healthCareDistrict': 'Pohjois-Pohjanmaa',
  'infectionSourceCountry': 'AUT',
  'infectionSource': 'unknown'},
 {'id': '105',
  'date': '2020-03-12T11:45:00.000Z',
  'healthCareDistrict': 'Pohjois-Pohjanmaa',
  'infectionSourceCountry': 'AUT',
  'infectionSource': 'unknown'},
 {'id': '106',
  'date': '2020-03-12T11:45:00.000Z',
  'healthCareDistrict': 'Pohjois-Pohjanmaa',
  'infectionSourceCountry': 'AUT',
  'infectionSource': 'unknown'},
 {'id': '107',
  'date': '2020-03-12T11:45:00.000Z',
  'healthCareDistrict': 'Pohjois-Pohjanmaa',
  'infectionSourceCountry': 'AUT',
  'infectionSource': 'unknown'},
 {'id': '108',
  'date': '2020-03-12T11:45:00.000Z',
  'healthCareDistrict': 'Pohjois-Pohjanmaa',
  'infectionSourceCountry': 'AUT',
  'infectionSource': 'unknown'},
 {'id': '109',
  'date': '2020-03-12T11:45:00.000Z',
  'healthCareDistrict': 'Keski-Suomi',
  'infectionSourceCountry': 'ITA',
  'infectionSource': 'unknown'},
 {'id': '110',
  'date': '2020-03-12T11:45:00.000Z',
  'healthCareDistrict': 'Etelä-Pohjanmaa',
  'infectionSourceCountry': '',
  'infectionSource': 'unknown'},
 {'id': '111',
  'date': '2020-03-12T20:05:00.000Z',
  'healthCareDistrict': 'HUS',
  'infectionSourceCountry': 'AUT',
  'infectionSource': 'unknown'},
 {'id': '112',
  'date': '2020-03-12T20:15:00.000Z',
  'healthCareDistrict': 'HUS',
  'infectionSourceCountry': '',
  'infectionSource': 'unknown'},
 {'id': '113',
  'date': '2020-03-13T07:20:00.000Z',
  'healthCareDistrict': 'HUS',
  'infectionSourceCountry': '',
  'infectionSource': 'unknown'},
 {'id': '114',
  'date': '2020-03-13T07:20:00.000Z',
  'healthCareDistrict': 'HUS',
  'infectionSourceCountry': '',
  'infectionSource': 'unknown'},
 {'id': '115',
  'date': '2020-03-13T07:20:00.000Z',
  'healthCareDistrict': 'HUS',
  'infectionSourceCountry': '',
  'infectionSource': 'unknown'},
 {'id': '116',
  'date': '2020-03-13T07:20:00.000Z',
  'healthCareDistrict': 'HUS',
  'infectionSourceCountry': '',
  'infectionSource': 'unknown'},
 {'id': '117',
  'date': '2020-03-13T07:20:00.000Z',
  'healthCareDistrict': 'HUS',
  'infectionSourceCountry': '',
  'infectionSource': 'unknown'},
 {'id': '118',
  'date': '2020-03-13T07:20:00.000Z',
  'healthCareDistrict': 'HUS',
  'infectionSourceCountry': '',
  'infectionSource': 'unknown'},
 {'id': '119',
  'date': '2020-03-13T07:20:00.000Z',
  'healthCareDistrict': 'HUS',
  'infectionSourceCountry': '',
  'infectionSource': 'unknown'},
 {'id': '120',
  'date': '2020-03-13T07:20:00.000Z',
  'healthCareDistrict': 'HUS',
  'infectionSourceCountry': '',
  'infectionSource': 'unknown'},
 {'id': '121',
  'date': '2020-03-13T07:20:00.000Z',
  'healthCareDistrict': 'HUS',
  'infectionSourceCountry': '',
  'infectionSource': 'unknown'},
 {'id': '122',
  'date': '2020-03-13T07:20:00.000Z',
  'healthCareDistrict': 'HUS',
  'infectionSourceCountry': '',
  'infectionSource': 'unknown'},
 {'id': '123',
  'date': '2020-03-13T07:20:00.000Z',
  'healthCareDistrict': 'HUS',
  'infectionSourceCountry': '',
  'infectionSource': 'unknown'},
 {'id': '124',
  'date': '2020-03-13T07:20:00.000Z',
  'healthCareDistrict': 'HUS',
  'infectionSourceCountry': '',
  'infectionSource': 'unknown'},
 {'id': '125',
  'date': '2020-03-13T07:20:00.000Z',
  'healthCareDistrict': 'HUS',
  'infectionSourceCountry': '',
  'infectionSource': 'unknown'},
 {'id': '126',
  'date': '2020-03-13T07:20:00.000Z',
  'healthCareDistrict': 'HUS',
  'infectionSourceCountry': '',
  'infectionSource': 'unknown'},
 {'id': '127',
  'date': '2020-03-13T07:20:00.000Z',
  'healthCareDistrict': 'HUS',
  'infectionSourceCountry': '',
  'infectionSource': 'unknown'},
 {'id': '128',
  'date': '2020-03-13T07:20:00.000Z',
  'healthCareDistrict': 'HUS',
  'infectionSourceCountry': '',
  'infectionSource': 'unknown'},
 {'id': '129',
  'date': '2020-03-13T07:20:00.000Z',
  'healthCareDistrict': 'HUS',
  'infectionSourceCountry': '',
  'infectionSource': 'unknown'},
 {'id': '130',
  'date': '2020-03-13T08:55:00.000Z',
  'healthCareDistrict': 'Pirkanmaa',
  'infectionSourceCountry': 'FIN',
  'infectionSource': 'unknown'},
 {'id': '131',
  'date': '2020-03-13T08:55:00.000Z',
  'healthCareDistrict': 'Pirkanmaa',
  'infectionSourceCountry': 'AUT',

In [480]:
pd.json_normalize(json_data["confirmed"])

,id,date,healthCareDistrict,infectionSourceCountry,infectionSource
0,1,2020-01-29T11:00:00.000Z,Lappi,CHN,unknown
1,2,2020-02-26T11:00:00.000Z,HUS,ITA,unknown
2,3,2020-03-01T11:00:00.000Z,HUS,FIN,2
3,4,2020-02-28T11:00:00.000Z,HUS,ITA,unknown
4,5,2020-03-01T11:00:00.000Z,HUS,FIN,4
...,...,...,...,...,...
1413,1423,2020-03-31T08:00:00.000Z,HUS,None,unknown
1414,1424,2020-03-31T08:00:00.000Z,HUS,None,unknown
1415,1425,2020-03-31T08:00:00.000Z,HUS,None,unknown
1416,1426,2020-03-31T08:00:00.000Z,HUS,None,unknown
1417,1427,2020-03-31T08:00:00.000Z,HUS,None,unknown

In [482]:
pd.json_normalize(json_data["deaths"])

    id                      date healthCareDistrict
0    1  2020-03-21T13:10:00.000Z                HUS
1    2  2020-03-25T08:50:00.000Z         Kanta-Häme
2    3  2020-03-25T09:10:00.000Z                HUS
3    4  2020-03-26T10:30:00.000Z        Päijät-Häme
4    5  2020-03-26T11:00:00.000Z                HUS
5    6  2020-03-27T14:15:00.000Z                HUS
6    7  2020-03-27T14:15:00.000Z               None
7    8  2020-03-28T12:30:00.000Z  Pohjois-Pohjanmaa
8    9  2020-03-28T14:55:00.000Z               None
9   10  2020-03-29T14:00:00.000Z               None
10  11  2020-03-29T14:00:00.000Z               None
11  12  2020-03-30T12:45:00.000Z               None
12  13  2020-03-30T12:45:00.000Z               None
13  14  2020-03-31T14:00:00.000Z               None
14  15  2020-03-31T14:00:00.000Z               None
15  16  2020-03-31T14:00:00.000Z               None
16  17  2020-03-31T14:00:00.000Z               None